### ISSUE TITLE
A user has to move data/words.csv into his project

### ISSUE THREAD

**Issue by dottorblaster** [apdunston/random_words#1]
When importing this module into my project, things went bad:

```
iex(1)> RandomWords.adjective
** (EXIT from #PID<0.538.0>) shell process exited with reason: shutdown: failed to start child: RandomWords.WordServer
    ** (EXIT) an exception was raised:
        ** (File.Error) could not stream "data/words.csv": no such file or directory
            (elixir 1.10.3) lib/file/stream.ex:83: anonymous fn/3 in Enumerable.File.Stream.reduce/3
            (elixir 1.10.3) lib/stream.ex:1407: anonymous fn/5 in Stream.resource/3
            (elixir 1.10.3) lib/stream.ex:880: Stream.do_transform/5
            (elixir 1.10.3) lib/stream.ex:1609: Enumerable.Stream.do_each/4
            (elixir 1.10.3) lib/enum.ex:3383: Enum.reverse/1
            (elixir 1.10.3) lib/enum.ex:2982: Enum.to_list/1
            (random_words 1.0.0) lib/word_server.ex:34: RandomWords.WordServer.read_from_csv/0
            (random_words 1.0.0) lib/word_server.ex:12: RandomWords.WordServer.init/1
            (stdlib 3.13) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.13) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

I had to copy `data/words.csv` under my project's `data` directory to make it work.

**Comment by apdunston** [comment]
Well that's no good at all, is it? Like the other issue, thanks for reporting. I believe I have solved this in 1.0.1. Please try it out and confirm if you have time. Thank you!

**Comment by dottorblaster** [comment]
Thanks!!! Much appreciated :-) anyway, looks like the issue was not fixed :/ I pulled the `1.0.1` from Hex, but looks like there isn't any `data` directory inside the package 😣 

```
10:46:36 › ls /Users/blaster/Desktop/projects/xxx/deps/random_words/
LICENSE  README.md  hex_metadata.config  lib  mix.exs
```

**Comment by apdunston** [comment]
Grump grump. Thanks. Will circle back to this soon.

**Comment by apdunston** [comment]
@dottorblaster, I believe I have fixed the issue (with the proper use of a priv directory). I have also taken additional steps to verify the solution. If you could also verify, I'd much appreciate it.

**Comment by dottorblaster** [comment]
@apdunston it works! Thank you thank you thank you ❤️
